config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :rock_paper_scissor_rounds

  resources :games do
    member do
      put 'reject'
      put 'accept'
    end
    collection do
    end
  end

  resources :ranks

  resources :users do
    collection do
      put 'reset_stats/:id(.:format)', :to => 'users#reset_stats',
                                       :as => :reset_stats
    end
  end

  devise_for :user, :controllers => { registrations: 'registrations' }

  resources :general_forum_topics

  resources :discussion_topics

  resources :comments

  resources :faqs
  

end

app/models/faq.rb
class Faq < ActiveRecord::Base
  validates :question, presence: { :message => "can't be empty" }
end

app/controllers/faqs_controller.rb
class FaqsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]
  before_action :validate_admin!, only: [:new, :edit, :create, :update, :destroy]
  before_action :set_faq, only: [:show, :edit, :update, :destroy]

  def validate_admin!
    if !current_user.admin?
      redirect_to faqs_url, alert: 'Only admins may edit the faqs.'
    end
  end

  # GET /faqs
  # GET /faqs.json
  def index
    @faqs = Faq.all
    @faqs = @faqs.sort_by(&:created_at)
  end

  # GET /faqs/1
  # GET /faqs/1.json
  def show
  end

  # GET /faqs/new
  def new
    @faq = Faq.new
  end

  # GET /faqs/1/edit
  def edit
  end

  # POST /faqs
  # POST /faqs.json
  def create
    @faq = Faq.new(faq_params)

    respond_to do |format|
      if @faq.save
        format.html { redirect_to @faq, notice: 'Faq was successfully created.' }
        format.json { render :show, status: :created, location: @faq }
      else
        format.html { render :new }
        format.json { render json: @faq.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /faqs/1
  # PATCH/PUT /faqs/1.json
  def update
    respond_to do |format|
      if @faq.update(faq_params)
        format.html { redirect_to @faq, notice: 'Faq was successfully updated.' }
        format.json { render :show, status: :ok, location: @faq }
      else
        format.html { render :edit }
        format.json { render json: @faq.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /faqs/1
  # DELETE /faqs/1.json
  def destroy
    @faq.destroy
    respond_to do |format|
      format.html { redirect_to faqs_url, notice: 'Faq was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_faq
      @faq = Faq.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def faq_params
      params.require(:faq).permit(:question, :answer)
    end
end

app/helpers/faqs_helper.rb
module FaqsHelper
end

app/views/faqs/_form.html.erb
<%= form_for(@faq) do |f| %>
  <% if @faq.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@faq.errors.count, "error") %> prohibited this faq from being saved:</h2>

      <ul>
      <% @faq.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :question %><br>
    <%= f.text_field :question %>
  </div>
  <div class="field">
    <%= f.label :answer %><br>
    <%= f.text_area :answer %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/faqs/edit.html.erb
<h1>Editing FAQ</h1>

<%= render 'form' %>

<p><%= link_to 'Show', @faq %> | 
<%= link_to 'Back', faqs_path %></p>

app/views/faqs/index.html.erb
<h1>FAQs</h1>

<% if !@faqs.empty? %>
  <% @faqs.each do |faq| %>
    <article class="faq">
      <h4 class="faq">Q: <%= faq.question %></h4>
      <p><b>A:</b> <%= faq.answer %></p>
      <% if user_signed_in? and current_user.admin? %>
        <td><%= link_to 'Show', faq %></td>
        <td><%= link_to 'Edit', edit_faq_path(faq) %></td>
        <td><%= link_to 'Destroy', faq, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </article>
  <% end %>
<% else %>
  <h2>There are no recorded FAQs</h2>
<% end %>

<br>

<% if user_signed_in? and current_user.admin? %>
  <%= button_to 'New FAQ', new_faq_path, :method => "get" %>
<% end %>
<%= button_to 'Back', general_forum_topics_path, :method => "get" %>

app/views/faqs/new.html.erb
<h1>New FAQ</h1>

<%= render 'form' %>

<p><%= link_to 'Back', faqs_path %></p>

app/views/faqs/show.html.erb
<p>
  <strong>Question:</strong>
  <%= @faq.question %>
</p>

<p>
  <strong>Answer:</strong>
  <%= @faq.answer %>
</p>

<p><%= link_to 'Edit', edit_faq_path(@faq) %> | 
<%= link_to 'Back', faqs_path %></p>