config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :rock_paper_scissor_rounds

  resources :games do
    member do
      put 'reject'
      put 'accept'
    end
    collection do
    end
  end

  resources :ranks

  resources :users do
    collection do
      put 'reset_stats/:id(.:format)', :to => 'users#reset_stats',
                                       :as => :reset_stats
    end
  end

  devise_for :user, :controllers => { registrations: 'registrations' }

  resources :general_forum_topics

  resources :discussion_topics

  resources :comments

  resources :faqs
  

end

app/models/discussion_topic.rb
class DiscussionTopic < ActiveRecord::Base
  validates :title, presence: true
  validates :title, uniqueness: { case_sensitive: false }
  validates :description, presence: true
  validates_length_of :title, :maximum => 50
  validates_length_of :description, :maximum => 2000

  has_many :comments, :dependent => :destroy
  belongs_to :general_forum_topic

  def original_poster
    User.find self.user_id
  end

  def closed_status
    if self.closed
      'Closed'
    else
      'Open'
    end
  end

  def comments_count
    temp = 'discussion_topic_id = ' + self.id.to_s
    Comment.where(temp).count
  end

  def is_op?(some_id)
    some_id == self.user_id
  end

  def exist?
    !self.title.nil? && !self.description.nil?
  end

  # Deciding if this should be used or not
  #def show_title
  #  if self.title.size > 30
  #    self.title[0..30] + "..."
  #  else
  #    self.title
  #  end
  #end
end

app/controllers/discussion_topics_controller.rb
class DiscussionTopicsController < ApplicationController
  #before_action :authenticate_new, only:[:new]
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]
  before_action :set_discussion_topic, only: [:show, :edit, :update, :destroy]

  def index
    amount = 25
    if !params[:forum_id].nil?
      @forum = GeneralForumTopic.find params[:forum_id]
      @topics = @forum.discussion_topics
      @topics = @topics.order(created_at: :desc)

      if !(params[:page].nil?) && (params[:page].to_i > 0)
        @last_page = (@topics.count - 1) / amount + 1
        @next_available = (( @topics.limit(amount).offset((amount) * (params[:page].to_i)) ).size > 0)
        @previous_available = params[:page].to_i > 1
        @topics = @topics.limit(amount).offset(amount * (params[:page].to_i - 1))
      else
        redirect_to discussion_topics_url(:forum_id => params[:forum_id].to_i, :page => 1)
      end
    else
      redirect_to general_forum_topics_path
    end
  end

  def show
    amount = 10
    @comments = @topic.comments.order(created_at: :asc)
    if !(params[:page].nil?) && (params[:page].to_i > 0)
      @last_page = (@comments.count - 1) / amount + 1
      @next_available = (( @comments.limit(amount).offset((amount) * (params[:page].to_i)) ).size > 0)
      @previous_available = params[:page].to_i > 1
      @comments = @comments.limit(amount).offset(amount * (params[:page].to_i - 1))
    else
      redirect_to discussion_topic_url(@topic, :page => 1)
    end
  end

  def new
    @forum = GeneralForumTopic.find(params[:forum_id])
    @topic = DiscussionTopic.new
    if @forum.forum_access_required and !current_user.has_forum_access?
      redirect_to general_forum_topics_path, alert: 'You cannot make a topic for this forum.'
    end
  end

  def edit
    if !(valid_user(@topic.user_id) or current_user.has_forum_access?)
      redirect_to discussion_topics_path(forum_id: @topic.general_forum_topic.id), alert: 'You cannot edit this topic.'
    end
  end

  def create
    @topic = DiscussionTopic.new(discussion_topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: 'DiscussionTopic was successfully created.' }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @topic.update(discussion_topic_params)
        format.html { redirect_to @topic, notice: 'DiscussionTopic was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to discussion_topics_url, notice: 'DiscussionTopic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_discussion_topic
      @topic = DiscussionTopic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def discussion_topic_params
      params.require(:discussion_topic).permit(:title, :description, :user_id,
        :closed, :removed, :general_forum_topic_id)
    end
end

app/helpers/discussion_topics_helper.rb
module DiscussionTopicsHelper
end

app/views/discussion_topics/_edit_form.html.erb
<%= form_for(@topic) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% @topic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if current_user.has_forum_access? %>
    <div class="field">
      <%= f.label :general_forum_topic_id, "Forum" %><br>
      <%= f.select :general_forum_topic_id, options_from_collection_for_select(GeneralForumTopic.all, 'id', 'title') %>
    </div>

    <div class="field">
      <%= f.label :title %><br>
      <%= f.text_area :title, maxlength: 50, size: "30x2", placeholder: 'Enter title less then or equal to 50 characters' %>
    </div>

    <div class="field">
      <%= f.label :description %><br>
      <%= f.text_area :description, maxlength: 2000, size: "30x10", placeholder: 'Enter text less then or equal to 2000 characters' %>
    </div>
  <% else %>
    <h3><%= @topic.general_forum_topic.title %></h3>

    <strong>Title</strong>
    <p><%= @topic.title %></p>

    <strong>Description</strong>
    <p><%= @topic.description %></p>
  <% end %>

  <% if @topic.exist? %>
    <div class="actions">
      <%= f.label :closed, "Close this discussion?" %>
      <%= f.check_box :closed %>
    </div>

    <div class="actions">
      <%= f.label :removed, "Remove this discussion?" %>
      <%= f.check_box :removed %>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/discussion_topics/_form.html.erb
<%= form_for(@topic) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% @topic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.hidden_field :general_forum_topic_id, :value => params[:forum_id].to_i %>
  </div>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_area :title, maxlength: 50, size: "30x2", placeholder: 'Enter title less then or equal to 50 characters' %>
  </div>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, maxlength: 2000, size: "30x10", placeholder: 'Enter text less then or equal to 2000 characters' %>
  </div>

  <div class="hidden_fields">
    <%= f.hidden_field :user_id, :value => current_user.id %>
  </div>

  <% if @topic.exist? %>
    <div class="actions">
      <%= f.label :closed, "Close this discussion?" %>
      <%= f.check_box :closed %>
    </div>

    <div class="actions">
      <%= f.label :removed, "Remove this discussion?" %>
      <%= f.check_box :removed %>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/discussion_topics/edit.html.erb
<h1>Discussion Topic</h1>

<%= render 'edit_form' %>

<% if current_user.has_forum_access? %>
  <p><%= link_to 'Back', discussion_topics_path(forum_id: @topic.general_forum_topic.id) %> | 
  <%= link_to 'Delete', @topic, method: :delete, data: { confirm: 'Are you sure?' } %></p>
<% else %>
  <p><%= link_to 'Back', discussion_topics_path(forum_id: @topic.general_forum_topic.id) %></p>
<% end %>

app/views/discussion_topics/index.html.erb
<h1><%= @forum.name %></h1>

<% if !@topics.empty? %>
  <p>|
    Page <%= params[:page] %> |

    <%= link_to 'First', discussion_topics_url(:forum_id => @forum.id, :page => 1) %> |

    <% if @previous_available %>
      <%= previous_page "topics" %> |
    <% end %>

    <% if @next_available %>
      <%= next_page "topics" %> |
    <% end %>

    <%= link_to 'Last', discussion_topics_url(:forum_id => @forum.id, :page => @last_page) %> |
  </p>

  <div class="table-responsive">
    <table class="table">
      <thead>
        <tr>
          <th>Title</th>
          <th>Comments</th>
          <th>Status</th>
          <th>Options</th>
        </tr>
      </thead>
      <tbody>
        <% @topics.each do |topic| %>
          <tr>
            <td><%= link_to topic.title, topic %></td>
            <td><%= topic.comments_count %></td>
            <td><%= topic.closed_status %></td>
            <td>
              <% if user_signed_in? and current_user.has_forum_access? %>
                <%= link_to 'Edit', edit_discussion_topic_path(topic) %>
              <% else %>
                <%= link_to 'Enter', topic %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <p>|
    Page <%= params[:page] %> |

    <%= link_to 'First', discussion_topics_url(:forum_id => @forum.id, :page => 1) %> |

    <% if @previous_available %>
      <%= previous_page "topics" %> |
    <% end %>

    <% if @next_available %>
      <%= next_page "topics" %> |
    <% end %>

    <%= link_to 'Last', discussion_topics_url(:forum_id => @forum.id, :page => @last_page) %> |
  </p>

<% else %>
  <strong>There are no discussion topics for this section</strong>
<% end %>

<p><%= link_to 'New Topic', new_discussion_topic_path(forum_id: @forum.id) %> |
<%= link_to 'Back', general_forum_topics_path %></p>

app/views/discussion_topics/new.html.erb
<h1>New <%= @forum.name %> Topic</h1>

<%= render 'form' %>

<p><%= link_to 'Back', discussion_topics_path %></p>

app/views/discussion_topics/show.html.erb
<h1 style="word-wrap:break-word;"><%= @topic.title %></h1>

<strong>Original Poster:</strong>
  <p style="word-wrap:break-word;"><%= @topic.original_poster.name %></p>

<strong>Created At</strong>
  <p><%= @topic.created_at %></p>

<strong>Last Updated</strong>
  <p><%= @topic.updated_at %></p>

<% if !@comments.empty? %>
  <p>|
    Page <%= params[:page] %> |

    <%= link_to 'First', discussion_topic_url(:forum_id => params[:forum_id], :page => 1) %> |

    <% if @previous_available %>
      <%= previous_page "comments" %> |
    <% end %>

    <% if @next_available %>
      <%= next_page "comments" %> |
    <% end %>

    <%= link_to 'Last', discussion_topic_url(:forum_id => params[:forum_id], :page => @last_page) %> |
  </p>
<% end %>

<article class="topic">
  <div class="comment_info">
    <strong><%= @topic.original_poster.show_rank %> <%= @topic.original_poster.name %></strong>
    <% if @topic.original_poster.icon? %>
      <td><%= image_tag @topic.original_poster.icon.url(:small) %></td>
    <% end %>
    <p><%= @topic.created_at %></p>
  </div>
  <div class="comment_content">
    <p><strong>Topic Description</strong></p>
    <p style="word-wrap:break-word;"><%= @topic.description %></p>
  </div>
</article>

<% if !@comments.empty? %>
  <% @comments.each do |comment| %>
    <article class="topic">
      <div class="comment_info">
        <strong><%= comment.commenter.show_rank %> <%= comment.commenter.name %></strong>
        <% if comment.commenter.icon? %>
          <td><%= image_tag comment.commenter.icon.url(:small) %></td>
        <% end %>
        <p><%= comment.created_at %></p>
        <% if user_signed_in? and (current_user == @topic.original_poster or current_user.has_forum_access?) %>
          <p><%= link_to 'Edit', edit_comment_path(comment) %></p>
        <% end %>
      </div>
      <div class="comment_content">
        <p style="word-wrap:break-word;"><%= comment.show_content %></p>
      </div>
    </article>
  <% end %>

  <p>|
    Page <%= params[:page] %> |

    <%= link_to 'First', discussion_topic_url(:forum_id => params[:forum_id], :page => 1) %> |

    <% if @previous_available %>
      <%= previous_page "comments" %> |
    <% end %>

    <% if @next_available %>
      <%= next_page "comments" %> |
    <% end %>

    <%= link_to 'Last', discussion_topic_url(:forum_id => params[:forum_id], :page => @last_page) %> |
  </p>

<% else %>
  <h3>There are no comments yet</h3>
<% end %>

<p><%= link_to 'Comment', new_comment_url(topic_id: @topic.id) %> | 
<%= link_to 'Back', discussion_topics_path(forum_id: @topic.general_forum_topic.id) %></p>
<% if user_signed_in? && (@topic.is_op?(current_user.id) || current_user.has_forum_access?) %>
  <p><%= link_to 'Edit', edit_discussion_topic_path(@topic) %></p>
<% end %>