config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :rock_paper_scissor_rounds

  resources :games do
    member do
      put 'reject'
      put 'accept'
    end
    collection do
    end
  end

  resources :ranks

  resources :users do
    collection do
      put 'reset_stats/:id(.:format)', :to => 'users#reset_stats',
                                       :as => :reset_stats
    end
  end

  devise_for :user, :controllers => { registrations: 'registrations' }

  resources :general_forum_topics

  resources :discussion_topics

  resources :comments

  resources :faqs
  

end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_length_of :user_name, :maximum => 24
  validates_length_of :first_name, :maximum => 24
  validates_length_of :last_name, :maximum => 24
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :user_name, presence: true
  validates :user_name, uniqueness: { case_sensitive: false }

  has_attached_file :icon, :styles => { :medium => "300x300>", :small => "100x100>", :tiny => "16x16" }
  validates_attachment_size :icon, :less_than => 5.megabytes
  validates_attachment_content_type :icon, :content_type => ['image/jpeg', 'image/png', 'image/gif']

  def active_for_authentication?
    super and (!self.is_disabled or self.admin? or self.master_admin?)
  end

  def name
    "#{user_name}"
  end

  def admin?
    self.admin
  end

  def master_admin?
    self.master_admin
  end

  def is_hidden?
    self.is_hidden
  end

  def is_disabled?
    self.is_disabled
  end

  def has_forum_access?
    self.forum_access or self.master_admin?
  end

  def has_user_access?
    self.has_user_stat_access? or self.has_user_profile_access? or self.has_give_user_access?
  end

  def has_user_stat_access?
    self.user_stat_access or self.master_admin?
  end

  def has_user_profile_access?
    self.user_profile_access or self.master_admin?
  end

  def has_game_access?
    self.game_access or self.master_admin?
  end

  def has_give_user_access?
    self.give_access or self.master_admin?
  end

  def list_access_rights
    temp = ""
    self.admin? ? temp += "Admin" : false
    self.has_forum_access? ? temp += ", Forum Access" : false
    self.has_user_stat_access? ? temp += ", User Stat Access" : false
    self.has_user_profile_access? ? temp += ", User Profile Access" : false
    self.has_game_access? ? temp += ", Game Access" : false
    self.has_give_user_access? ? temp += ", Give Access" : false
    self.master_admin ? temp += ", Master Admin" : false
    if temp.length == 0
      "None"
    else
      temp
    end
  end

  def rank
    Rank.find_by(:level => self.level)
  end

  def show_rank
    self.level.to_s + "-" + (Rank.find_by level: self.level).name
  end

  def next_rank
    if self.level < Rank.maximum("level")
      Rank.find_by(:level => (self.level + 1))
    else
      self.rank
    end
  end

  def previous_rank
    if self.level > Rank.minimum("level")
      Rank.find_by(:level => (self.level - 1))
    else
      self.rank
    end
  end

  #def level_up
  #  self.level += 1
  #end

  #def level_down
  #  self.level -= 1
  #end

  def rank_up
    self.update_attribute( :level, self.next_rank.level )
  end

  def rank_down
    self.update_attribute( :level, self.previous_rank.level )
  end

  def update_rank
    if self.exp < self.rank.exp_required
      self.rank_down
    elsif self.exp >= next_rank.exp_required
      self.rank_up
    end
  end

  def update_stats_wins
    self.update_attributes( :wins_count => (self.wins_count + 1),
                            :games_played_count => (self.games_played_count + 1),
                            :current_win_streak => (self.current_win_streak + 1) )
    if (self.current_win_streak > self.best_win_streak)
      self.update_attribute( :best_win_streak, self.current_win_streak )
    end
  end

  def update_stats_loses
    self.update_attributes( :loss_count => (self.loss_count + 1),
                            :games_played_count => (self.games_played_count + 1),
                            :current_win_streak => 0 )
  end

  def update_stats_ties
    self.update_attributes( :tie_count => (self.tie_count + 1),
                            :games_played_count => (self.games_played_count + 1) )
  end

  # This method returns int > 0 representing the exp gained for the game to record
  def wins_against(opponent_level)
    update_stats_wins
    exp_gained = self.calculate_win_exp_against(opponent_level)
    self.update_attributes( :exp => self.exp + exp_gained,
                            :coins => self.coins + exp_gained )
    self.update_rank
    return exp_gained
  end

  # This method returns int < 0 representing the exp lost for the game to record
  def loses_against(opponent_level)
    update_stats_loses
    exp_lost = self.calculate_lose_exp_against(opponent_level)
    if ( (check = (self.exp - exp_lost)) <= 0 )
      exp_lost = self.exp
      self.update_attribute( :exp, 0 )
    else
      self.update_attribute( :exp, check )
    end
    self.update_rank
    return exp_lost * -1
  end

  # Returns positive or negative int depending if user gained or loss exp
  def ties_against(opponent_level)
    update_stats_ties
    exp_change = self.calculate_tie_exp_against(opponent_level)
    self.update_attribute( :exp, self.exp + exp_change )
    self.update_rank
    return exp_change
  end

  def calculate_win_exp_against(opponent_level)
    base_exp = self.level
    level_difference_exp = opponent_level - self.level
    win_streak_multiplier = 1
    if current_win_streak == 2
      win_streak_multiplier = 1.5
    elsif current_win_streak > 2
      win_streak_multiplier = 2
    end

    return (base_exp + level_difference_exp) * 10 * win_streak_multiplier
  end

  # Returns a positive integer > 0 that represents exp lost
  def calculate_lose_exp_against(opponent_level)
    base_exp = self.level
    level_difference_exp = opponent_level - self.level

    if ((base_exp = base_exp - level_difference_exp) < 1)
      return 5
    else
      return base_exp * 10
    end
  end

  # Returns positive if you are lower leveled and negative if you are higher leveled
  def calculate_tie_exp_against(opponent_level)
    level_difference_exp = opponent_level - self.level
    return level_difference_exp * 5
  end

  def remove_coins(amount)
    self.coins -= amount
    if self.coins < 0
      self.coins = 0
    end
  end

  def add_coins(amount)
    self.coins += amount
  end

  def reset_stats
    self.wins_count = 0
    self.loss_count = 0
    self.tie_count = 0
    self.current_win_streak = 0
    self.best_win_streak = 0
    self.games_played_count = 0
    self.coins = 0
    self.exp = 0
    self.level = 1
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:index, :show, :edit, :update, :destroy, :reset_stats]
  before_action :set_user, only: [:show, :edit, :update, :destroy, :reset_stats]

  helper_method :sort_column, :sort_direction

  # GET /users
  # GET /users.json
  def index
    amount = 25
    @users = User.order(sort_column + " " + sort_direction)

    if !(params[:page].nil?) && (params[:page].to_i > 0)
      @last_page = (@users.count - 1) / amount + 1
      @next_available = (( @users.limit(amount).offset((amount) * (params[:page].to_i)) ).size > 0)
      @previous_available = params[:page].to_i > 1
      @users = @users.limit(amount).offset(amount * (params[:page].to_i - 1))
    else
      redirect_to users_url(:page => 1)
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    if (@user.is_hidden? && !current_user.has_user_access? && @user.id != current_user.id)
      redirect_to users_url
    end
  end

  # GET /users/new
  def new
    if !(user_signed_in?) or user_exists
      redirect_to users_url
    else
      @user = User.new
    end
  end

  # GET /users/1/edit
  def edit
    #if !(valid_user(@user.id) or !current_user.has_user_access?)
    if valid_user(@user.id) or current_user.has_user_access?
      
    else
      redirect_to users_url
    end
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def reset_stats
    @user = User.find(params[:id])
    @user.reset_stats
    @user.save!
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully reset.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :user_name, :games_played_count,
        :wins_count, :loss_count, :tie_count, :best_win_streak, :current_win_streak, :email,
        :encrypted_password, :icon, :is_disabled, :is_hidden, :coins, :exp, :level, :admin,
        :forum_access, :user_stat_access, :user_profile_access, :game_access, :give_access,
        :password )
    end

    # These two methods are used to make the table sortable.
    def sort_column
      User.column_names.include?(params[:sort]) ? params[:sort] : "user_name"
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_admin_form.html.erb
<%= form_for(@user, :html => { :multipart => true }) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if current_user.has_user_profile_access? %>
    <h4>Admin Profile Edits</h4>

    <div class="field">
      <%= f.label :first_name %><br>
      <%= f.text_field :first_name %>
    </div>

    <div class="field">
      <%= f.label :last_name %><br>
      <%= f.text_field :last_name %>
    </div>

    <div class="field">
      <%= f.label :user_name %><br>
      <%= f.text_field :user_name %>
    </div>

    <div class="field">
      <%= f.label :icon %><br>
      <%= f.file_field :icon %>
    </div>
  <% end %>

  <% if current_user.has_user_stat_access? %>
    <h4>Admin Stat Edits</h4>

    <div class="admin_field">
      <%= f.label :level %><br>
      <%= f.number_field :level, :min => Rank.minimum("level"), :max => Rank.maximum("level") %>
    </div>

    <div class="admin_field">
      <%= f.label :exp %><br>
      <%= f.number_field :exp, :min => 0, :max => Rank.maximum("exp_required") %>
    </div>

    <div id="flip">Show Ranks</div>
    <div id="panel">
      <table border="1">
        <thead>
          <tr>
            <th>Level</th>
            <th>Rank</th>
            <th>EXP Required</th>
          </tr>
        </thead>

        <tbody>
          <% Rank.all.sort_by(&:level).each do |rank| %>
            <tr>
              <td><%= rank.level %></td>
              <td><%= rank.name %></td>
              <td><%= rank.exp_required %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <div class="admin_field">
      <%= f.label :coins %><br>
      <%= f.number_field :coins, :min => 0 %>
    </div>

    <div class="admin_field">
      <%= f.label :games_played_count %><br>
      <%= f.number_field :games_played_count, :min => 0 %>
    </div>

    <div class="admin_field">
      <%= f.label :wins_count %><br>
      <%= f.number_field :wins_count, :min => 0 %>
    </div>

    <div class="admin_field">
      <%= f.label :loss_count %><br>
      <%= f.number_field :loss_count, :min => 0 %>
    </div>

    <div class="admin_field">
      <%= f.label :tie_count %><br>
      <%= f.number_field :tie_count, :min => 0 %>
    </div>

    <div class="admin_field">
      <%= f.label :best_win_streak %><br>
      <%= f.number_field :best_win_streak, :min => 0 %>
    </div>

    <div class="admin_field">
      <%= f.label :current_win_streak %><br>
      <%= f.number_field :current_win_streak, :min => 0 %>
    </div>

    <div class="admin_field">
      <%= f.label :is_disabled, "Disable this user?" %>
      <%= f.check_box :is_disabled %>
    </div>

    <div class="admin_field">
      <%= f.label :is_hidden, "Hide this user?" %>
      <%= f.check_box :is_hidden %>
    </div>
  <% end %>

  <% if current_user.has_give_user_access? %>
    <h4>Admin Access Rights</h4>

    <div class="admin_field">
      <%= f.label :admin, "Make admin?" %>
      <%= f.check_box :admin %>
    </div>

    <div class="admin_field">
      <%= f.label :forum_access, "Give forum access?" %>
      <%= f.check_box :forum_access %>
    </div>

    <div class="admin_field">
      <%= f.label :user_stat_access, "Give user stat access?" %>
      <%= f.check_box :user_stat_access %>
    </div>

    <div class="admin_field">
      <%= f.label :user_profile_access, "Give user profile access?" %>
      <%= f.check_box :user_profile_access %>
    </div>

    <div class="admin_field">
      <%= f.label :game_access, "Give game access?" %>
      <%= f.check_box :game_access %>
    </div>

    <div class="admin_field">
      <%= f.label :give_access, "Give access right authorization?" %>
      <%= f.check_box :give_access %>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>

<script> 
  $(document).ready(function(){
    $("#flip").click(function(){
      $("#panel").slideToggle("fast");
    });
  });
</script>

app/views/users/_form.html.erb
<%= form_for(@user, :html => { :multipart => true }) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>

  <div class="field">
    <%= f.label :user_name %><br>
    <%= f.text_field :user_name %>
  </div>

  <div class="field">
    <%= f.label :icon %><br>
    <%= f.file_field :icon %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<% if current_user.has_user_access? %>
  <%= render 'admin_form' %>
<% else %>
  <%= render 'form' %>
<% end %>

<p><%= link_to 'Back', @user %><p>

app/views/users/index.html.erb
<h1>Users</h1>

<% if !@users.empty? %>

  <p>|
    Page <%= params[:page] %> |
  
    <%= link_to 'First', users_url(:page => 1, :sort => params[:sort], :direction => params[:direction]) %> |

    <% if @previous_available %>
      <%= previous_page "users" %> |
    <% end %>

    <% if @next_available %>
      <%= next_page "users" %> |
    <% end %>

    <%= link_to 'Last', users_url(:page => @last_page, :sort => params[:sort], :direction => params[:direction]) %> |
  </p>

  <div class="table-responsive">
    <table border="4" class="table table-striped table-condensed">
      <thead>
        <tr>
          <th>Icon</th>
          <th><%= sortable "user_name", "User Name" %></th>
          <th><%= sortable "level", "Level" %></th>
          <th><%= sortable "games_played_count", "Games Played" %></th>
          <th><%= sortable "wins_count", "Wins" %></th>
          <th><%= sortable "loss_count", "Loss" %></th>
          <th><%= sortable "tie_count", "Ties" %></th>
          <% if user_signed_in? %>
            <th colspan="1">Options</th>
          <% end %>
        </tr>
      </thead>

      <tbody>
        <% @users.each do |user| %>

          <% if !user.is_hidden? or current_user.has_user_access? or user.id == current_user.id %>
            <tr>
              <% if user.icon? %>
                <td><%= image_tag user.icon.url(:tiny) %></td>
              <% else %>
                <td></td>
              <% end %>
              <td class="name_column"><%= link_to user.user_name, user_path(user.id) %></td>
              <td><%= user.show_rank %></td>
              <td><%= user.games_played_count %></td>
              <td><%= user.wins_count %></td>
              <td><%= user.loss_count %></td>
              <td><%= user.tie_count %></td>
              <% if user_signed_in? %>
                <% if user.is_disabled? %>
                  <td>Disabled</td>
                <% elsif user.id != current_user.id %>
                  <td><%= link_to 'Challenge', new_game_url(user_1_id: current_user.id, user_2_id: user.id) %></td>
                <% else %>
                  <td></td>
                <% end %>
              <% end %>
            </tr>
          <% end %>

        <% end %>
      </tbody>
    </table>
  </div>

  <p>|
    Page <%= params[:page] %> |

    <%= link_to 'First', users_url(:page => 1, :sort => params[:sort], :direction => params[:direction]) %> |

    <% if @previous_available %>
      <%= previous_page "users" %> |
    <% end %>

    <% if @next_available %>
      <%= next_page "users" %> |
    <% end %>

    <%= link_to 'Last', users_url(:page => @last_page, :sort => params[:sort], :direction => params[:direction]) %> |
  </p>

<% else %>
  <h2>There are no existing users</h2>
<% end %>

<p title="Click challenge to challange a user to a game!"><%= link_to 'Need Help?', faqs_path %></p>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<p><%= link_to 'Back', users_path %></p>

app/views/users/show.html.erb
<h2>Profile: <%= @user.user_name %></h2>
<h3>Level: <%= @user.show_rank %></h3>

<% if @user.admin? %>
  <strong>Administrator</strong><br>
<% end %>

<% if @user.icon? %>
  <td><%= image_tag @user.icon.url(:small) %></td>
<% end %>

<% if current_user.id == @user.id or current_user.has_user_stat_access? %>
  <p>
    <strong>EXP:</strong>
    <%= @user.exp %>
  </p>
  <p>
    <strong>Coins:</strong>
    <%= @user.coins %>
  </p>
  
  <p>
    <strong>First name:</strong>
    <%= @user.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= @user.last_name %>
  </p>
<% end %>

<h3>Stats</h3>

<p>
  <strong>Games Played:</strong>
  <%= @user.games_played_count %>
</p>

<p>
  <strong>Wins Total:</strong>
  <%= @user.wins_count %>
</p>

<p>
  <strong>Loss Total:</strong>
  <%= @user.loss_count %>
</p>

<p>
  <strong>Ties Total:</strong>
  <%= @user.tie_count %>
</p>

<p>
  <strong>Best Win Streak:</strong>
  <%= @user.best_win_streak %>
</p>

<p>
  <strong>Current Win Streak:</strong>
  <%= @user.current_win_streak %>
</p>

<% if current_user.admin? %>
  <p>
    <strong>Disabled:</strong>
    <%= @user.is_disabled %>
  </p>

  <p>
    <strong>Hidden:</strong>
    <%= @user.is_hidden %>
  </p>

  <% if current_user.id == @user.id or current_user.has_give_user_access? %>
    <h3>Admin Access Rights</h3>
    <p><%= @user.list_access_rights %></p>
  <% end %>
<% end %><br>

<% if current_user.id == @user.id or current_user.has_user_access? %>
  <p><%= link_to 'Edit', edit_user_path(@user) %> | 
     <%= link_to 'Find Players', users_path %> | 
     <%= link_to 'View History', games_path(:user_id => @user.id) %></p>
<% else %>
  <p><%= link_to 'Find Players', users_path %> | 
  <%= link_to 'View History', games_path(:user_id => @user.id) %></p>
<% end %>

<% if current_user.has_user_stat_access? %>
  <p><%= link_to 'RESET Stats', reset_stats_users_path(@user), method: :put, data: { confirm: 'Are you sure you want to reset this user?' } %></p>
<% end %>

<% if current_user.has_user_profile_access? %>
  <p><%= link_to 'DELETE User', @user, method: :delete, data: { confirm: 'Are you sure? Remember to delete associated games.' } %></p>
<% end %>