config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :rock_paper_scissor_rounds

  resources :games do
    member do
      put 'reject'
      put 'accept'
    end
    collection do
    end
  end

  resources :ranks

  resources :users do
    collection do
      put 'reset_stats/:id(.:format)', :to => 'users#reset_stats',
                                       :as => :reset_stats
    end
  end

  devise_for :user, :controllers => { registrations: 'registrations' }

  resources :general_forum_topics

  resources :discussion_topics

  resources :comments

  resources :faqs
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Arcade</title>
    <%= favicon_link_tag 'favicon.ico' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>
  <body>
    <div class="navbar navbar-default navbar-static-top">
      <div class="container-fluid">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Arcade</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Users", users_url %></li>
            <li><%= link_to "Ranks", ranks_path %> </li>
            <li><%= link_to "Games History", games_url %></li>
            <li><%= link_to "Forum", general_forum_topics_path %></li>
            <% if user_signed_in? %>
              <li><%= link_to (User.find current_user.id).user_name, user_path(current_user.id) %></li>
            <% end %>
          </ul>

          <p class="navbar-text pull-right">
            <% if user_signed_in? %>
              Logged in as <strong><%= (User.find current_user.id).user_name %></strong>.
              <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
              <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link' %>
            <% else %>
              <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link' %> |
              <%= link_to "Login", new_user_session_path, :class => 'navbar-link' %>
            <% end %>
          </p>
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">

        <% if notice %>
          <p class="alert alert-success"><%= notice %></p>
        <% end %>
        <% if alert %>
          <p class="alert alert-danger"><%= alert %></p>
        <% end %>
        
        <div class="col-lg-9" id="main"><%= yield %></div>
        <div class="col-lg-3" id="side_bar">
          <h2>How to play!</h2>
          <ol>
            <li>Create an account</li>
            <li>Sign in</li>
            <li>Click Users</li>
            <li>Find someone to Challenge</li>
            <li>Select the round count and click Send Challenge</li>
            <li>Wait for opponent to accept (manually refresh page)</li>
            <li>Play!</li>
          </ol>
        </div>
      </div>
    </div>

    <div class="footer">
      <hr>
      <p>&copy; Company 2014</p>
    </div>
  </body>
</html>